name: Publish Extension

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Install publishing tools
        run: |
          npm install -g @vscode/vsce@2.22.0
          npm install -g ovsx
        
      - name: Build
        run: npm run compile
        
      - name: Package Extension
        run: vsce package

      - name: Upload VSIX as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: "*.vsix"
          retention-days: 90

      - name: Publish to VS Code Marketplace
        if: startsWith(github.ref, 'refs/tags/v')
        run: vsce publish -p ${{ secrets.VSCE_PAT }}

      # - name: Publish to Open VSX Registry
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   run: ovsx publish *.vsix -p ${{ secrets.OVSX_PAT }}

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "*.vsix"
          draft: false
          prerelease: false
          generate_release_notes: true
