name: Publish Extension

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Install publishing tools
        run: |
          npm install -g @vscode/vsce@2.22.0
          npm install -g ovsx
        
      - name: Build
        run: npm run compile
        
      - name: Package and Publish Extension
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          vsce package
          vsce publish -p ${{ secrets.VSCE_PAT }}
          ovsx publish -p ${{ secrets.OVSX_PAT }}
        
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
